function headerTitle() {
    const headers = [
      "Monday to Thursday",
      "Friday",
      "Saturdays",
      "Sundays",
      "School Holiday",
      "Others",
      "",
      "End Year",
      "Duration FROM:",
      "Duration TO:",
      "Monday to Thursday",
      "Friday",
      "Saturdays",
      "Sundays",
      "School Holiday",
      "Others",
      "Total mileage for the period",
      "Base Rate (with 2% inflation)*",
      "Yearly SF Cost (excl UFC)",
      "Fuel Rate (UFC)",
      "Fuel Cost",
      "Unit Rate inclusive of Fuel Rate (Base Rate + Fuel Rate)",
      "SF Cost (incl Fuel Cost) for the period",
      "No. of months in time period",
      "Estimated Lease Fee per time period",
      "Total Cost (SF + LF)",
      "Total Amount Required",
      "",
      "Annual Mileage:",
      "Annual SF:",
      "Annual LF:",
      "Annual Cost:",
      "VO Start Date:",
      "VO End Date:",
      "Annual Cost (For CRR calc)",
    ];
    return headers;
  }
  
  export default headerTitle;